export const INGREDIENTS = [
  "あまいミツ",
  "あんみんトマト",
  "ほっこりポテト",
  "あったかジンジャー",
  "リラックスカカオ",
  "げきからハーブ",
  "ピュアなオイル",
  "マメミート",
  "モーモーミルク",
  "とくせんエッグ",
  "とくせんリンゴ",
  "あじわいキノコ",
  "ふといながねぎ",
  "おいしいシッポ",
  "ワカクサ大豆",
  "ワカクサコーン",
  "めざましコーヒー",
  "ずっしりカボチャ",
  "つやつやアボカド",
] as const

export type Ingredient = (typeof INGREDIENTS)[number]

export interface PokemonData {
  name: string
  ingredient: Ingredient
  slot: string
  recipe: string
  energy: number
  requiredCapacity: number
}

export const POKEMON_DATA: PokemonData[] = [
  {
    name: "カモネギ",
    ingredient: "ふといながねぎ",
    slot: "A枠",
    recipe: "からくちネギもりカレー",
    energy: 5900,
    requiredCapacity: 25,
  },
  {
    name: "ピカチュウ",
    ingredient: "とくせんリンゴ",
    slot: "A枠",
    recipe: "とくせんアップルカレー",
    energy: 4500,
    requiredCapacity: 20,
  },
  {
    name: "ミルタンク",
    ingredient: "モーモーミルク",
    slot: "A枠",
    recipe: "モーモーホットミルク",
    energy: 5200,
    requiredCapacity: 22,
  },
  {
    name: "ラッキー",
    ingredient: "とくせんエッグ",
    slot: "A枠",
    recipe: "スクランブルエッグ",
    energy: 4800,
    requiredCapacity: 18,
  },
  {
    name: "コダック",
    ingredient: "あじわいキノコ",
    slot: "B枠",
    recipe: "キノコのほうしポトフ",
    energy: 3900,
    requiredCapacity: 30,
  },
  {
    name: "ビークイン",
    ingredient: "あまいミツ",
    slot: "A枠",
    recipe: "ハニードリンク",
    energy: 6200,
    requiredCapacity: 28,
  },
  {
    name: "ドードリオ",
    ingredient: "ワカクサコーン",
    slot: "A枠",
    recipe: "コーンシチュー",
    energy: 4100,
    requiredCapacity: 24,
  },
  {
    name: "カビゴン",
    ingredient: "ワカクサ大豆",
    slot: "B枠",
    recipe: "ワカクサ大豆ハンバーグ",
    energy: 5500,
    requiredCapacity: 35,
  },
  {
    name: "プクリン",
    ingredient: "あんみんトマト",
    slot: "A枠",
    recipe: "トマトサラダ",
    energy: 3600,
    requiredCapacity: 16,
  },
  {
    name: "ゲンガー",
    ingredient: "リラックスカカオ",
    slot: "A枠",
    recipe: "チョコレートケーキ",
    energy: 5800,
    requiredCapacity: 32,
  },
  {
    name: "ウインディ",
    ingredient: "げきからハーブ",
    slot: "A枠",
    recipe: "スパイシーカレー",
    energy: 5100,
    requiredCapacity: 26,
  },
  {
    name: "ヤドラン",
    ingredient: "おいしいシッポ",
    slot: "A枠",
    recipe: "しっぽテールスープ",
    energy: 4700,
    requiredCapacity: 29,
  },
  {
    name: "ニャース",
    ingredient: "ピュアなオイル",
    slot: "B枠",
    recipe: "ヘルシーオイルサラダ",
    energy: 3400,
    requiredCapacity: 19,
  },
  {
    name: "ゴローン",
    ingredient: "ほっこりポテト",
    slot: "A枠",
    recipe: "ポテトサラダ",
    energy: 4200,
    requiredCapacity: 21,
  },
  {
    name: "エーフィ",
    ingredient: "めざましコーヒー",
    slot: "A枠",
    recipe: "モーニングコーヒー",
    energy: 5000,
    requiredCapacity: 27,
  },
  {
    name: "リザードン",
    ingredient: "あったかジンジャー",
    slot: "A枠",
    recipe: "ジンジャーティー",
    energy: 4600,
    requiredCapacity: 23,
  },
  {
    name: "ケンタロス",
    ingredient: "マメミート",
    slot: "A枠",
    recipe: "ミートパスタ",
    energy: 5300,
    requiredCapacity: 31,
  },
  {
    name: "オニゴーリ",
    ingredient: "ずっしりカボチャ",
    slot: "A枠",
    recipe: "かぼちゃのポタージュ",
    energy: 4400,
    requiredCapacity: 33,
  },
  {
    name: "ルカリオ",
    ingredient: "つやつやアボカド",
    slot: "A枠",
    recipe: "アボカドサラダ",
    energy: 5600,
    requiredCapacity: 34,
  },
]
